// Central place for all app paths. Keep keys stable and reuse them everywhere.

export const all_routes = {
  // Landing / Main
  home: "/home",
  dashboards: "/dashboards",
  dashboard1: "/dashboard1",
  dashboard2: "/dashboard2",
  dashboard3: "/dashboard3",
  DrugPage: "/drug-page",

  // Search flows
  drugSearch: "/search1",
  insuranceSearch: "/search-insurance",
  search3: "/search3",
  search2: "/search-classes",

  // Commerce
  cart: "/cart",
  orderHistory: "/orderHistory",

  // Communications
  chat: "/chat",
  voiceCall: "/voice-call",
  videoCall: "/video-call",
  calendar: "/calendar",
  email: "/email",
  emailCompose: "/email-compose",
  emailDetails: "/email-details",
  contacts: "/contacts",
  contactList: "/contact-list",

  // Invoicing
  invoice: "/invoice",
  invoiceDetails: "/invoice-details",
  addInvoice: "/add-invoice",
  editInvoice: "/edit-invoice",
  manageInvoices: "/manage-invoices",
  manageInvoicesDetails: "/manage-invoices-details",
  manageEditInvoices: "/manage-edit-invoices",
  manageAddInvoices: "/manage-add-invoices",

  // Healthcare
  patients: "/patients",
  allPatientsList: "/all-patients-list",
  addPatient: "/add-patient",
  editPatient: "/edit-patients",
  patientDetails: "/patient-details",
  patientDetailsAppointment: "/patient-details-appointment",
  patientDetailsVitalSign: "/patient-details-vital-sign",
  patientDetailsVisitHistory: "/patient-details-visit-history",
  patientDetailsLabResults: "/patient-details-lab-results",
  patientdetailsPrescription: "/patient-details-prescription",
  patientetailsMedicalHistory: "/patient-details-medical-history",
  patientetailsDocuments: "/patient-details-documents",
  doctors: "/doctors",
  allDoctorsList: "/all-doctors-list",
  addDoctors: "/add-doctors",
  editDoctors: "/edit-doctors",
  doctorDetails: "/doctors-details",
  appointments: "/appointments",
  visits: "/visits",
  startVisits: "/start-visits",
  labResults: "/lab-results",
  medicalResults: "/medical-results",
  pharmacy: "/pharmacy",
  requests: "/requests",

  // Manage
  staff: "/staffs",
  notifications: "/notifications",
  messages: "/messages",
  generalSettings: "/general-settings",
  securitySettings: "/security-settings",
  preferencesSettings: "/preferences-settings",
  appearanceSettings: "/appearance-settings",
  notificationsSettings: "/notifications-settings",
  userPermissionsSettings: "/user-permissions-settings",
  plansBillingsSettings: "/plans-billings-settings",
  permissionSettings: "/permission-settings",

  // Auth & pages
  login: "/login",
  signUp: "/sign-up",
  forgotPassword: "/forgot-password",
  changePassword: "/change-password",
  lockScreen: "/lock-screen",
  error404: "/error-404",
  error500: "/error-500",
  starterPage: "/starter-page",
  comingSoon: "/coming-soon",
  underMaintenance: "/under-maintenance",
  privacyPolicy: "/privacy-policy",
  termsAndConditions: "/terms-and-conditions",

  // Layout demos
  layoutMini: "/layout-mini",
  layoutHoverview: "/layout-hoverview",
  layoutHidden: "/layout-hidden",
  layoutFullwidth: "/layout-fullwidth",
  layoutRtl: "/layout-rtl",
  layoutDark: "/layout-dark",

  // UI – Base
  uiAccordion: "/ui-accordion",
  uiAlerts: "/ui-alerts",
  uiAvatar: "/ui-avatar",
  uiBadges: "/ui-badges",
  uiBreadcrumb: "/ui-breadcrumb",
  uiButtons: "/ui-buttons",
  uiButtonsGroup: "/ui-buttons-group",
  uiCards: "/ui-cards",
  uiCarousel: "/ui-carousel",
  uiCollapse: "/ui-collapse",
  uiDropdowns: "/ui-dropdowns",
  uiRatio: "/ui-ratio",
  uiGrid: "/ui-grid",
  uiImages: "/ui-images",
  uiLinks: "/ui-links",
  uiListGroup: "/ui-list-group",
  uiModals: "/ui-modals",
  uiOffcanvas: "/ui-offcanvas",
  uiPagination: "/ui-pagination",
  uiPlaceholders: "/ui-placeholders",
  uiPopovers: "/ui-popovers",
  uiProgress: "/ui-progress",
  uiScrollspy: "/ui-scrollspy",
  uiSpinner: "/ui-spinner",
  uiNavTabs: "/ui-nav-tabs",
  uiToasts: "/ui-toasts",
  uiTooltips: "/ui-tooltips",
  uiTypography: "/ui-typography",
  uiUtilities: "/ui-utilities",
  themeTest: "/theme-test",

  // UI – Advanced
  uiDragula: "/ui-dragula",
  uiClipboard: "/ui-clipboard",
  uiRangeslider: "/ui-rangeslider",
  uiSweetalerts: "/ui-sweetalerts",
  uiLightbox: "/ui-lightbox",
  uiRating: "/ui-rating",
  uiScrollbar: "/ui-scrollbar",

  // Forms
  formBasicInputs: "/form-basic-inputs",
  formCheckboxRadios: "/form-checkbox-radios",
  formInputGroups: "/form-input-groups",
  formGridGutters: "/form-grid-gutters",
  formMask: "/form-mask",
  formFileupload: "/form-fileupload",
  formHorizontal: "/form-horizontal",
  formVertical: "/form-vertical",
  formFloatingLabels: "/form-floating-labels",
  formValidation: "/form-validation",
  formSelect: "/form-select",
  formWizard: "/form-wizard",
  formPickers: "/form-pickers",
  formEditors: "/form-editors",
  feedBack: "/feed",
  insuranceDetails: "/InsuranceDetails/:insuranceName",
  insuranceBinDetails: "/InsuranceBINDetails/:insuranceName",
  insurancePcnDetails: "/InsurancePCNDetails/:insuranceName",
  // Tables
  tablesBasic: "/tables-basic",
  dataTables: "/data-tables",

  // Charts
  chartApex: "/chart-apex",
  chartC3: "/chart-c3",
  chartMorris: "/chart-morris",
  chartFlot: "/chart-flot",
  chartPeity: "/chart-peity",

  // Icons
  iconFontawesome: "/icon-fontawesome",
  iconTabler: "/icon-tabler",
  iconBootstrap: "/icon-bootstrap",
  iconRemix: "/icon-remix",
  iconFeather: "/icon-feather",
  iconIonic: "/icon-ionic",
  iconMaterial: "/icon-material",
  iconPe7: "/icon-pe7",
  iconSimpleline: "/icon-simpleline",
  iconThemify: "/icon-themify",
  iconWeather: "/icon-weather",
  iconTypicon: "/icon-typicon",
  iconFlag: "/icon-flag",
};
